In [16]:
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

In [18]:
# Load the raw data
df_price = pd.read_csv("../data/raw/eth_usd_dataset.csv")
df_post = pd.read_csv("../data/raw/eth_post.csv")

In [19]:
# Exploring df_price

# 'High'  : The highest price of the asset during the trading period
# 'Low'   : The lowest price of the asset during the trading period
# 'Open'  : The price of the asset at the start of the trading period
# 'Close' : The price of the asset at the end of the trading period
# 'Volume': The total number of shares/contracts traded during the period

print(df_price.head(3))
print("----------------------")
print(df_price.info())
print("----------------------")

         Date               Close               High                Low  \
0         NaN             ETH-USD            ETH-USD            ETH-USD
1  2017-11-09   320.8840026855469  329.4519958496094  307.0559997558594
2  2017-11-10  299.25299072265625  324.7179870605469     294.5419921875

                Open     Volume
0            ETH-USD    ETH-USD
1  308.6449890136719  893249984
2  320.6709899902344  885985984
----------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2610 entries, 0 to 2609
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2609 non-null   object
 1   Close   2610 non-null   object
 2   High    2610 non-null   object
 3   Low     2610 non-null   object
 4   Open    2610 non-null   object
 5   Volume  2610 non-null   object
dtypes: object(6)
memory usage: 122.5+ KB
None
----------------------

In [20]:
print(df_price.isnull().sum())
print("----------------------")
print(df_price.describe())
print("----------------------")
df_price = df_price.iloc[1:].reset_index(drop=True)

Date      1
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64
----------------------
              Date              Close               High                 Low  \
count         2609               2610               2610                2610
unique        2609               2609               2609                2609
top     2017-11-09  3156.509521484375  1919.264404296875  1564.0318603515625
freq             1                  2                  2                   2

                     Open   Volume
count                2610     2610
unique               2609     2610
top     205.1739959716797  ETH-USD
freq                    2        1
----------------------

In [21]:
# Exploring df_post
print(df_post.head(3))
print("--------------")
print(df_post.info())

   created_utc subreddit                                             body  \
0   1579408968  ethereum  Yeah that s infallible Logic you re using there
1   1579408860  ethereum                               RemindMe  6 Months
2   1579408651  ethereum  Thats what people said here about 2018 and 2019

   score
0      6
1      3
2     -5
--------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488910 entries, 0 to 488909
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   created_utc  488910 non-null  int64
 1   subreddit    488910 non-null  object
 2   body         488901 non-null  object
 3   score        488910 non-null  int64
dtypes: int64(2), object(2)
memory usage: 14.9+ MB
None

In [22]:
print(df_post.isna().sum())
print("--------------")
print(df_post.describe())

created_utc    0
subreddit      0
body           9
score          0
dtype: int64
--------------
        created_utc          score
count  4.889100e+05  488910.000000
mean   1.625597e+09       3.111356
std    1.514739e+07      17.079133
min    1.577837e+09    -314.000000
25%    1.618529e+09       1.000000
50%    1.628716e+09       1.000000
75%    1.637006e+09       2.000000
max    1.648771e+09    2507.000000

In [23]:
df_post["Date"] = pd.to_datetime(df_post["created_utc"], unit='s').dt.date
print("Reddit Post Date Range")
print(df_post["Date"].min())
print(df_post["Date"].max())

print("Eth Price Date Range")
df_price["Date"] = pd.to_datetime(df_price["Date"]).dt.date
print(df_price["Date"].min())
print(df_price["Date"].max())

Reddit Post Date Range
2020-01-01
2022-03-31
Eth Price Date Range
2017-11-09
2024-12-30

In [24]:
# Adjusting df_price date range

start_date = pd.to_datetime("2020-01-01").date()
end_date = pd.to_datetime("2022-03-31").date()

df_price = df_price[(df_price["Date"] >= start_date) & (df_price["Date"] <= end_date)].reset_index(drop=True)

In [25]:
# Dropping null from df_post

df_post = df_post.dropna(subset=['body']).reset_index(drop=True)
print(df_post.isna().sum())

created_utc    0
subreddit      0
body           0
score          0
Date           0
dtype: int64

In [26]:
df_post.to_csv("../data/processed/cleaned_eth_post.csv", index=False)
df_price.to_csv("../data/processed/cleaned_eth_price.csv",index=False)

In [27]:
display(df_price.head(3))
display(df_price.info())
display(df_post.head(3))
display(df_post.info())

,Date,Close,High,Low,Open,Volume
0,2020-01-01,130.802001953125,132.83535766601562,129.1982879638672,129.6306610107422,7935230330
1,2020-01-02,127.4101791381836,130.82003784179688,126.95491027832031,130.82003784179688,8032709256
2,2020-01-03,134.1717071533203,134.55401611328125,126.49002075195312,127.41126251220703,10476845358

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821 entries, 0 to 820
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    821 non-null    object
 1   Close   821 non-null    object
 2   High    821 non-null    object
 3   Low     821 non-null    object
 4   Open    821 non-null    object
 5   Volume  821 non-null    object
dtypes: object(6)
memory usage: 38.6+ KB

None

,created_utc,subreddit,body,score,Date
0,1579408968,ethereum,Yeah that s infallible Logic you re using there,6,2020-01-19
1,1579408860,ethereum,RemindMe 6 Months,3,2020-01-19
2,1579408651,ethereum,Thats what people said here about 2018 and 2019,-5,2020-01-19

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488901 entries, 0 to 488900
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   created_utc  488901 non-null  int64
 1   subreddit    488901 non-null  object
 2   body         488901 non-null  object
 3   score        488901 non-null  int64
 4   Date         488901 non-null  object
dtypes: int64(2), object(3)
memory usage: 18.7+ MB

None